name = "advent"
version = "1.0.0"

description = "ğŸ„ An Advent of Code runner for your Gleam project!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "advent" }
links = [{ title = "Sponsor", href = "https://github.com/sponsors/giacomocavalieri" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
global_value = ">= 1.0.0 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
string_width = ">= 3.3.1 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
